Fix bug in constructing jar file introduced in 1688.
Causes problem like:
java.lang.IllegalArgumentException: InputStream cannot be null
	at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:117)
	at uk.me.parabola.mkgmap.build.LocatorConfig.loadConfig(LocatorConfig.java:70)
	at uk.me.parabola.mkgmap.build.LocatorConfig.<init>(LocatorConfig.java:47)


git-svn-id: http://svn.parabola.me.uk/mkgmap/trunk@1692 25d90789-57f7-4ee0-8453-03a3dfeeeb22